services:
  db:
    image: mariadb:10.11
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=adminpresta
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=presta_user
      - MYSQL_PASSWORD=adminpresta
    networks:
      - presta-net

  prestashop:
    image: prestashop/prestashop:8.1
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    environment:
      - DB_SERVER=db
      - DB_USER=presta_user
      - DB_PASSWD=adminpresta
      - DB_NAME=prestashop
      - PS_INSTALL_AUTO=0
    networks:
      - presta-net

networks:
  presta-net:

volumes:
  db_data: